"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
#
# Fail-closed: DEBUG now defaults to False, so a deployment that forgets to
# set it never silently boots in debug mode. Local development must set
# DEBUG=True in its .env (see .env.example) to get the previous convenient
# behavior back — that's the one deliberate, explicit opt-in, not a default.
#
# SECRET_KEY mirrors the same gate: the insecure hardcoded fallback below
# only exists to make `manage.py runserver` work out of the box in DEBUG
# mode, and is unreachable whenever DEBUG=False. A real deployment that
# omits SECRET_KEY now fails to boot with an explicit error instead of
# silently reusing a value that is checked into source control.


def _resolve_secret_key(debug, get_config=config):
    if debug:
        return get_config(
            "SECRET_KEY",
            default="django-insecure-**f5&8s#wb(__j1n#cqpv^s2k-ft)o&b7ee37mbk98$ja&b+dp",
        )
    return get_config("SECRET_KEY")


DEBUG = config("DEBUG", default=False, cast=bool)

SECRET_KEY = _resolve_secret_key(DEBUG)

# Comma-separated in the environment, e.g. ALLOWED_HOSTS=my-backend.onrender.com
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "apps.accounts",
    "apps.experiences",
    "apps.payments",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves collected static files directly from the app process — no
    # separate static host needed for this stage. Must stay right after
    # SecurityMiddleware (WhiteNoise's own requirement).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
#
# DATABASE_URL (e.g. Render's managed Postgres connection string) takes
# over when set. Without it, local dev keeps using the exact same SQLite
# file as before — nothing about local development changes.

DATABASE_URL = config("DATABASE_URL", default="", cast=str)

if DATABASE_URL:
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}  # type: ignore
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    # Unchanged Django default — kept explicit because defining STORAGES at
    # all replaces the whole dict, not just the key(s) below.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Email

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}


AUTH_USER_MODEL = "accounts.User"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # Opt-in per view via `throttle_classes`/`throttle_scope` (see
    # apps.accounts.views) — deliberately not set as DEFAULT_THROTTLE_CLASSES,
    # so the rest of the API stays unthrottled. Only the auth endpoints that
    # are realistic brute-force/enumeration targets use these scopes.
    "DEFAULT_THROTTLE_RATES": {
        "login": "10/min",
        "register": "10/hour",
        "token_refresh": "30/min",
    },
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
}


# ==========================
# CORS
# ==========================

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=Csv(),
)

CORS_ALLOW_CREDENTIALS = True


# ==========================
# HTTPS atrás do proxy (Render)
# ==========================
#
# Render (e PaaS equivalentes) terminam TLS num proxy e repassam HTTP puro
# para o container, sinalizando o esquema original via X-Forwarded-Proto.
# Sem isto, request.is_secure() (usado por CSRF, redirects, etc.) sempre
# veria a conexão como insegura. Seguro de manter sempre ligado: só importa
# quando esse header realmente vem de um proxy em que confiamos.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Vazio por padrão (nada muda localmente). Em produção, defina com a URL
# pública real, ex.: CSRF_TRUSTED_ORIGINS=https://my-backend.onrender.com
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Segue o mesmo padrão do resto do arquivo: reproduz o comportamento local
# atual por padrão (DEBUG=True -> cookies/redirect inseguros, como sempre
# foi) e só fica estrito quando DEBUG=False for setado em produção. Pode
# ainda ser sobrescrito individualmente via env se necessário.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)


# Cloudflare R2 (S3-compatible storage)
# Keep these values out of source control.  The application continues to boot
# without them so local work that does not request an upload is unaffected.
R2_ACCOUNT_ID = config("R2_ACCOUNT_ID", default="")
R2_ACCESS_KEY_ID = config("R2_ACCESS_KEY_ID", default="")
R2_SECRET_ACCESS_KEY = config("R2_SECRET_ACCESS_KEY", default="")
R2_BUCKET_NAME = config("R2_BUCKET_NAME", default="")
R2_PRESIGNED_URL_TTL_SECONDS = config(
    "R2_PRESIGNED_URL_TTL_SECONDS", default=900, cast=int
)

# Por quanto tempo uma Media fica em upload_status=PENDING antes de ser
# considerada abandonada (upload nunca confirmado via .../complete/) e
# limpa (objeto R2 + registro) na próxima vez que a quota de mídia do
# draft precisar ser calculada. Ponto único de verdade — nunca hardcode
# esse número em mais de um lugar (ver apps.experiences.services.media_cleanup).
PENDING_MEDIA_EXPIRATION_MINUTES = config(
    "PENDING_MEDIA_EXPIRATION_MINUTES", default=60, cast=int
)


# Mercado Pago
# Keep these values out of source control.  The application continues to boot
# without them; MercadoPagoClient only raises if it is actually instantiated
# without an access token configured.
MP_ACCESS_TOKEN = config("MP_ACCESS_TOKEN", default="")
MP_PUBLIC_KEY = config("MP_PUBLIC_KEY", default="")
MP_ENV = config("MP_ENV", default="sandbox")
# Assinatura secreta usada para validar o header x-signature dos webhooks
# (Suas integrações > Webhooks > Configurar notificação > revelar chave).
MP_WEBHOOK_SECRET = config("MP_WEBHOOK_SECRET", default="")
