# Generated by Django 5.2.7 on 2026-08-13 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_plans',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_process', 'Em processamento'), ('action_required', 'Aguardando ação (Pix)'), ('approved', 'Aprovado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado'), ('expired', 'Expirado'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('external_reference', models.CharField(max_length=128, unique=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('mp_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_sync_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='experiences.experiencedraft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.plan')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='payments_owner_i_268e06_idx'), models.Index(fields=['draft', '-created_at'], name='payments_draft_i_9b5f77_idx')],
                'constraints': [models.UniqueConstraint(fields=('draft', 'attempt_number'), name='uniq_draft_attempt'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_process', 'action_required'])), fields=('draft',), name='uniq_active_payment_per_draft')],
            },
        ),
    ]
