# Generated by Django 6.1 on 2026-08-13 04:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_initial_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.CharField(max_length=64, unique=True)),
                ('topic', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processed', 'Processado'), ('failed', 'Falhou')], default='received', max_length=20)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['topic', 'resource_id'], name='payment_web_topic_c4f4bd_idx')],
            },
        ),
    ]
