# Generated by Django 6.1 on 2026-08-30 00:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_restore_original_plan_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='payments.plan')),
                ('redeemed_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_plan_discounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'plan', 'is_active'], name='payment_pla_email_aa07a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('email', 'plan'), name='uniq_active_discount_per_email_plan')],
            },
        ),
    ]
