# Generated by Django 6.1 on 2026-09-04 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0010_experiencedraft_galaxy_live_music_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLoginToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_login_tokens', to='experiences.experiencedraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_login_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recovery_login_tokens',
            },
        ),
        migrations.CreateModel(
            name='CartRecoveryMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('1h', '1 hora'), ('24h', '24 horas'), ('72h', '72 horas')], max_length=8)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped_no_contact', 'Sem contato'), ('skipped_not_configured', 'Canal não configurado')], max_length=32)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_messages', to='experiences.experiencedraft')),
            ],
            options={
                'db_table': 'cart_recovery_messages',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('draft', 'stage', 'channel'), name='uniq_cart_recovery_message')],
            },
        ),
    ]
