import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadataBase resolves every relative URL used in metadata (including the
// Open Graph images built per-experience in app/e/[slug]/page.tsx) into an
// absolute one. Hardcoded to the official domain rather than derived from
// an env var: this only affects <meta> tag values read by external
// crawlers/link-preview bots (WhatsApp, etc.), never same-origin requests
// from the app itself, so it does not need to track NEXT_PUBLIC_API_URL or
// vary between the parallel domains during the memoverse.com.br migration.
export const metadata: Metadata = {
  metadataBase: new URL("https://memoverse.com.br"),
  title: "MemoVerse",
  description: "Generated by create next app",
  openGraph: {
    siteName: "MemoVerse",
    locale: "pt_BR",
    type: "website",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
