# Generated by Django 6.1 on 2026-09-02 23:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('preview_completed', 'Preview concluído'), ('pricing_viewed', 'Preço visualizado'), ('signup_started', 'Cadastro iniciado'), ('signup_completed', 'Cadastro concluído'), ('checkout_viewed', 'Checkout visualizado'), ('payment_started', 'Pagamento iniciado'), ('payment_failed', 'Pagamento falhou'), ('payment_approved', 'Pagamento aprovado'), ('publication_completed', 'Publicação concluída')], max_length=40)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('draft_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'funnel_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='funnel_even_name_6942e0_idx'), models.Index(fields=['session_id'], name='funnel_even_session_fa244d_idx')],
            },
        ),
    ]
