# Generated by Django 6.1 on 2026-08-12 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('awaiting_payment', 'Aguardando pagamento'), ('payment_failed', 'Pagamento falhou'), ('paid', 'Pago'), ('published', 'Publicado')], default='draft', max_length=32)),
                ('experience_type', models.CharField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('letter', models.TextField(blank=True)),
                ('short_message', models.TextField(blank=True)),
                ('music_provider', models.CharField(default='none', max_length=32)),
                ('music_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('photo', 'Foto'), ('video', 'Vídeo')], max_length=10)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('upload_status', models.CharField(choices=[('pending', 'Pendente'), ('uploaded', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='experiences.experiencedraft')),
            ],
            options={
                'db_table': 'experience_media',
                'ordering': ['media_type', 'sort_order', 'created_at'],
            },
        ),
    ]
