# Generated by Django 6.1 on 2026-08-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedraft',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencedraft',
            name='slug',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
