# Generated by Django 6.1 on 2026-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_experiencedraft_claim_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedraft',
            name='context_answer',
            field=models.TextField(blank=True),
        ),
    ]
