# Generated by Django 6.1 on 2026-08-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_experiencedraft_context_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
