# Generated by Django 6.1 on 2026-08-26 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0008_media_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='experiences.experiencedraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_recipients',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'draft'), name='uniq_user_draft_recipient')],
            },
        ),
    ]
