# Generated by Django 6.1 on 2026-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_experiencerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedraft',
            name='galaxy_live_music_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
